name: Build HShop
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build:ci
      # - name: Upload production-ready build files
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: production-files
      #     path: ./dist
      - name: Archive Release
        uses: thedoctor0/zip-release@develop
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'

      - name: Push Build to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./dist/*"
          token: ${{ secrets.TOKEN }}      